name: Deploy Frontend to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your preferred Node version
      
      - name: Check Node and npm versions
        run: |
          node -v
          npm -v


      - name: Debug current directory
        run: |
          pwd
          ls -la
          ls -la frontend

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 cp ./frontend/dist/index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html
          aws s3 sync ./frontend/dist/assets s3://${{ secrets.AWS_S3_BUCKET }}/assets --delete
